name: Publish

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0 # needed for versioning
      - name: Set up JDK 1.17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'microsoft'
      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: "${{ runner.os }}-bluemapsignmarkers-${{ hashFiles('**/*.gradle*') }}"
          restore-keys: |
            ${{ runner.os }}-bluemapsignmarkers-
      - name: make gradle wrapper executable
        run: chmod +x ./gradlew
      - name: Build with Gradle
        env:
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
        run: ./gradlew modrinth
